INSERT INTO routes_registry (
    service_name, feature_name, method, downstream_url, transactional, route_class,
    timeout_ms, retry_count, required_scope, is_active, description
) VALUES
('smartbank', 'registrasi_login_user', 'POST', 'http://localhost:8101/smartbank/registrasi_login_user', FALSE, 'read', 5000, 0, 'payment:write', TRUE, 'SmartBank user registration and login route'),
('smartbank', 'manajemen_saldo', 'GET', 'http://localhost:8101/smartbank/manajemen_saldo', FALSE, 'read', 5000, 0, 'payment:read', TRUE, 'SmartBank balance and transaction history route'),
('smartbank', 'transfer_antar_user', 'POST', 'http://localhost:8101/smartbank/transfer_antar_user', TRUE, 'transactional', 5000, 0, 'payment:write', TRUE, 'SmartBank user transfer route'),
('smartbank', 'pembayaran_transaksi', 'POST', 'http://localhost:8101/smartbank/pembayaran_transaksi', TRUE, 'transactional', 5000, 0, 'payment:write', TRUE, 'SmartBank payment endpoint for Gateway fee and ecosystem transactions'),
('smartbank', 'pinjaman_loan', 'POST', 'http://localhost:8101/smartbank/pinjaman_loan', TRUE, 'transactional', 5000, 0, 'payment:write', TRUE, 'SmartBank loan request route'),
('smartbank', 'pajak_biaya', 'POST', 'http://localhost:8101/smartbank/pajak_biaya', TRUE, 'transactional', 5000, 0, 'payment:write', TRUE, 'SmartBank tax and fee route'),
('smartbank', 'ledger_transaksi', 'GET', 'http://localhost:8101/smartbank/ledger_transaksi', FALSE, 'read', 5000, 0, 'payment:read', TRUE, 'SmartBank ledger read route'),
('smartbank', 'biaya_layanan_bank', 'POST', 'http://localhost:8101/smartbank/biaya_layanan_bank', TRUE, 'transactional', 5000, 0, 'payment:write', TRUE, 'SmartBank service fee route'),
('marketplace', 'manajemen_produk', 'POST', 'http://localhost:8102/marketplace/manajemen_produk', FALSE, 'read', 5000, 0, 'marketplace:write', TRUE, 'Marketplace product management route'),
('marketplace', 'browse_produk', 'GET', 'http://localhost:8102/marketplace/browse_produk', FALSE, 'read', 5000, 0, 'marketplace:read', TRUE, 'Marketplace product browsing route'),
('marketplace', 'checkout', 'POST', 'http://localhost:8102/marketplace/checkout', TRUE, 'transactional', 5000, 0, 'marketplace:write', TRUE, 'Marketplace checkout route'),
('marketplace', 'integrasi_pembayaran', 'POST', 'http://localhost:8102/marketplace/integrasi_pembayaran', TRUE, 'transactional', 5000, 0, 'marketplace:write', TRUE, 'Marketplace payment integration route'),
('marketplace', 'status_order', 'GET', 'http://localhost:8102/marketplace/status_order', FALSE, 'read', 5000, 0, 'marketplace:read', TRUE, 'Marketplace order status route'),
('marketplace', 'biaya_layanan_marketplace', 'POST', 'http://localhost:8102/marketplace/biaya_layanan_marketplace', TRUE, 'transactional', 5000, 0, 'marketplace:write', TRUE, 'Marketplace service fee route'),
('pos', 'input_transaksi', 'POST', 'http://localhost:8103/pos/input_transaksi', FALSE, 'read', 5000, 0, 'pos:write', TRUE, 'POS transaction input route'),
('pos', 'generate_tagihan', 'POST', 'http://localhost:8103/pos/generate_tagihan', FALSE, 'read', 5000, 0, 'pos:write', TRUE, 'POS invoice generation route'),
('pos', 'pembayaran', 'POST', 'http://localhost:8103/pos/pembayaran', TRUE, 'transactional', 5000, 0, 'pos:write', TRUE, 'POS payment route'),
('pos', 'riwayat_transaksi', 'GET', 'http://localhost:8103/pos/riwayat_transaksi', FALSE, 'read', 5000, 0, 'pos:read', TRUE, 'POS transaction history route'),
('pos', 'biaya_layanan_pos', 'POST', 'http://localhost:8103/pos/biaya_layanan_pos', TRUE, 'transactional', 5000, 0, 'pos:write', TRUE, 'POS service fee route'),
('supplierhub', 'manajemen_bahan_baku', 'POST', 'http://localhost:8104/supplierhub/manajemen_bahan_baku', FALSE, 'read', 5000, 0, 'supplier:write', TRUE, 'SupplierHub raw material management route'),
('supplierhub', 'order_bahan', 'POST', 'http://localhost:8104/supplierhub/order_bahan', FALSE, 'read', 5000, 0, 'supplier:write', TRUE, 'SupplierHub material order route'),
('supplierhub', 'konfirmasi_stok', 'POST', 'http://localhost:8104/supplierhub/konfirmasi_stok', FALSE, 'read', 5000, 0, 'supplier:write', TRUE, 'SupplierHub stock confirmation route'),
('supplierhub', 'pembayaran', 'POST', 'http://localhost:8104/supplierhub/pembayaran', TRUE, 'transactional', 5000, 0, 'supplier:write', TRUE, 'SupplierHub payment route'),
('supplierhub', 'biaya_layanan_supplier', 'POST', 'http://localhost:8104/supplierhub/biaya_layanan_supplier', TRUE, 'transactional', 5000, 0, 'supplier:write', TRUE, 'SupplierHub service fee route'),
('logistikita', 'request_pengiriman', 'POST', 'http://localhost:8105/logistikita/request_pengiriman', FALSE, 'read', 5000, 0, 'logistics:write', TRUE, 'LogistiKita shipping request route'),
('logistikita', 'tracking_status', 'GET', 'http://localhost:8105/logistikita/tracking_status', FALSE, 'read', 5000, 0, 'logistics:read', TRUE, 'LogistiKita tracking status route'),
('logistikita', 'biaya_pengiriman', 'POST', 'http://localhost:8105/logistikita/biaya_pengiriman', FALSE, 'read', 5000, 0, 'logistics:write', TRUE, 'LogistiKita shipping cost route'),
('logistikita', 'pembayaran_logistik', 'POST', 'http://localhost:8105/logistikita/pembayaran_logistik', TRUE, 'transactional', 5000, 0, 'logistics:write', TRUE, 'LogistiKita logistics payment route'),
('logistikita', 'biaya_layanan_logistik', 'POST', 'http://localhost:8105/logistikita/biaya_layanan_logistik', TRUE, 'transactional', 5000, 0, 'logistics:write', TRUE, 'LogistiKita service fee route'),
('umkm_insight', 'ambil_data_transaksi', 'GET', 'http://localhost:8106/umkm_insight/ambil_data_transaksi', FALSE, 'read', 5000, 0, 'analytics:read', TRUE, 'UMKM Insight transaction data route'),
('umkm_insight', 'analisis_penjualan', 'GET', 'http://localhost:8106/umkm_insight/analisis_penjualan', FALSE, 'read', 5000, 0, 'analytics:read', TRUE, 'UMKM Insight sales analysis route'),
('umkm_insight', 'dashboard', 'GET', 'http://localhost:8106/umkm_insight/dashboard', FALSE, 'read', 5000, 0, 'analytics:read', TRUE, 'UMKM Insight read-only dashboard route'),
('umkm_insight', 'biaya_akses_analytics', 'POST', 'http://localhost:8106/umkm_insight/biaya_akses_analytics', TRUE, 'transactional', 5000, 0, 'analytics:write', TRUE, 'UMKM Insight analytics subscription fee route') AS new
ON DUPLICATE KEY UPDATE
    downstream_url = new.downstream_url,
    transactional = new.transactional,
    route_class = new.route_class,
    timeout_ms = new.timeout_ms,
    retry_count = new.retry_count,
    required_scope = new.required_scope,
    is_active = new.is_active,
    description = new.description;
